# Generated by Django 4.1.7 on 2023-03-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishliststring',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
