# Generated by Django 4.1.7 on 2023-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_wishliststring_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wishliststring',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
